name: Set Up Stuart
description: Install Python requirements and prepare Stuart dependencies

runs:
  using: composite
  steps:
    - name: Install Python dependencies
      shell: pwsh
      run: python -m pip install -r pip-requirements.txt

    - name: Set up Stuart dependencies
      shell: pwsh
      run: stuart_setup -c .pytool/CISettings.py

    - name: Update Stuart dependencies
      shell: pwsh
      run: stuart_update -c .pytool/CISettings.py
