jobs:
  - job: SourceChecks
    displayName: Stuart CI
    pool:
      type: windows
    variables:
      WindowsContainerImage: onebranch.azurecr.io/windows/ltsc2022/vse2022:latest
      GIT_CONFIG_COUNT: "2"
      GIT_CONFIG_KEY_0: core.autocrlf
      GIT_CONFIG_VALUE_0: "false"
      GIT_CONFIG_KEY_1: core.longpaths
      GIT_CONFIG_VALUE_1: "true"
      ob_outputDirectory: $(Build.ArtifactStagingDirectory)/SOURCE_CHECKS
      ob_nugetPublishing_enabled: false
      ob_createvpack_enabled: false
    steps:
      - template: /.azuredevops/templates/stuart-setup.yml@self

      - script: >-
          stuart_ci_build
          -c .pytool/CISettings.py
          --disable-all
          GuidCheck=run
          LineEndingCheck=run
          UncrustifyCheck=run
        displayName: Run Stuart CI

      - task: PublishTestResults@2
        displayName: Publish Stuart Results
        condition: succeededOrFailed()
        inputs:
          testResultsFormat: JUnit
          testResultsFiles: Build/TestSuites.xml
          testRunTitle: Stuart CI
          failTaskOnFailedTests: true
