name: Run Stuart Source Checks
description: Run the mu_msvm Stuart CI plugins

runs:
  using: composite
  steps:
    - name: Run Stuart CI
      shell: pwsh
      run: >-
        stuart_ci_build
        -c .pytool/CISettings.py
        --disable-all
        GuidCheck=run
        LineEndingCheck=run
        UncrustifyCheck=run
