
name: $(SourceBranchName)_$(Date:yyyyMMdd_HHmmss)$(Rev:.r)

# https://aka.ms/obpipelines/triggers
trigger:
  batch: False
  branches:
    include:
    - official/*
pr: none

variables:
- template: data/vars.yml
# Because we have a template, we must use name/value to add more.
- name: PRdot
  value: ''

extends:
  template: common.yaml
  parameters:
    base: v2/Microsoft.Official.yml # EXTEND MICROSOFT.OFFICIAL.YML
    pipeline: Official
    publishNuget: True
