# https://aka.ms/obpipelines/triggers
trigger: none

parameters:

# This controls only Nuget create, not Vpack creation.
# Due to upstream code/policy, vpacks cannot be created in the PR pipeline.
# The official "CI" pipeline, which creates vpacks, can be run against PRs with approval.
- name: PublishPRNuget
  displayName: Publish Nuget Pkg for this PR for testing?
  type: boolean
  default: False

variables:
- template: data/vars.yml
# Because we have a template, we must use name/value to add more.
- name: PRdot
  value: 'PR.'

extends:
  template: common.yaml
  parameters:
    base: v2/Microsoft.NonOfficial.yml # https://aka.ms/obpipelines/templates
    pipeline: PR

    # This controls only Nuget create, not Vpack creation.
    # Due to upstream code/policy, vpacks cannot be created in the PR pipeline.
    # The official "CI" pipeline, which creates vpacks, can be run against PRs with approval.
    publishNuget: ${{parameters.PublishPRNuget}}
