jobs:
- job: SourceChecks
  displayName: Stuart Source Checks
  pool:
    type: windows
  variables:
    WindowsContainerImage: onebranch.azurecr.io/windows/ltsc2022/vse2022:latest
    ScriptsDir: .azuredevops/pipelines/OneBranch/scripts
    GIT_TERMINAL_PROMPT: '0'
    GIT_CONFIG_COUNT: '2'
    GIT_CONFIG_KEY_0: core.autocrlf
    GIT_CONFIG_VALUE_0: 'false'
    GIT_CONFIG_KEY_1: core.longpaths
    GIT_CONFIG_VALUE_1: 'true'
    ob_outputDirectory: $(Build.ArtifactStagingDirectory)/SOURCE_CHECKS
    ob_nugetPublishing_enabled: false
    ob_createvpack_enabled: false
  steps:
  - task: NuGetAuthenticate@1
    displayName: Authenticate NuGet Feed
    inputs: {nuGetServiceConnections: WindowsPartners_NugetFeedConnection}

  - task: PipAuthenticate@1
    displayName: Authenticate Pip Feed
    inputs: {artifactFeeds: $(System.TeamProject)/$(System.TeamProject)_PublicPackages}

  - script: python $(ScriptsDir)/set_repo_auth.py set
    displayName: Set ADO Repo Auth
    env: {SYSTEM_ACCESSTOKEN: $(System.AccessToken)}

  - script: python $(ScriptsDir)/source_checks.py --setup
    displayName: Run Stuart Source Checks

  - task: PublishTestResults@2
    displayName: Publish Source Check Results
    condition: succeededOrFailed()
    inputs:
      testResultsFormat: JUnit
      testResultsFiles: Build/TestSuites.xml
      testRunTitle: Stuart Source Checks
      failTaskOnFailedTests: true

  - task: CopyFiles@2
    displayName: Stage Source Check Logs
    condition: succeededOrFailed()
    continueOnError: true
    inputs:
      SourceFolder: Build
      Contents: |
        CI_BUILDLOG.*
        SETUPLOG.*
        UPDATE_LOG.*
        TestSuites.xml
        MsvmPkg/**
      TargetFolder: $(ob_outputDirectory)

  - script: python $(ScriptsDir)/set_repo_auth.py unset
    displayName: Unset ADO Repo Auth
    condition: always()
