trigger:
  branches:
    include:
      - main

pr:
  branches:
    include:
      - '*'

resources:
  repositories:
    - repository: mu_devops
      type: github
      endpoint: microsoft
      name: microsoft/mu_devops
      ref: main

variables:
  vm_image: 'windows-latest'
  tool_chain: 'VS2022'

jobs:
- job: BuildMatrix
  displayName: 'Build for All Platforms (X64/ARM64, Debug/Release)'
  pool:
    vmImage: $(vm_image)

  strategy:
    matrix:
      TARGET_DEBUG_X64:
        Build.Target: 'DEBUG'
        Build.Arch: 'X64'
        Suffix: 'DEBUG'
      TARGET_RELEASE_x64:
        Build.Target: 'RELEASE'
        Build.Arch: 'X64'
        Suffix: 'RELEASE'
      TARGET_DEBUG_AARCH64:
        Build.Target: 'DEBUG'
        Build.Arch: 'ARM64'
        Suffix: 'DEBUG'
      TARGET_RELEASE_AARCH64:
        Build.Target: 'RELEASE'
        Build.Arch: 'ARM64'
        Suffix: 'RELEASE'

  steps:
    - checkout: self
      clean: true
    - template: Steps/BuildPlatform.yml@mu_devops
      parameters:
        tool_chain_tag: $(tool_chain)
        build_target: $(Build.Target)
        build_file: MsvmPkg/PlatformBuild.py
        build_flags: "-a $(Build.Arch)"
        artifacts_binary: "**/MSVM.fd"
        artifacts_other: "**/unit_test_results/*"
        publish_artifacts: true
    - task: PowerShell@2
      displayName: 'Show build variables'
      inputs:
        targetType: inline
        script: |
          Write-Host "Build Target: $(Build.Target)"
          Write-Host "Build Arch: $(Build.Arch)"
          Write-Host "Tool Chain: $(tool_chain)"